In [76]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.python.ops import math_ops
from tensorflow.python.framework import constant_op
from tensorflow.python.keras import backend_config
import numpy as np

In [58]:
def _constant_to_tensor(x, dtype):
  return constant_op.constant(x, dtype=dtype)

In [59]:
epsilon = backend_config.epsilon

# Data Types

## Numpy value generation and operation

Generate array with 20 random binary number. You can use function from np.random

In [80]:
x =  np.random.randint(0,2,size=20)
print(x)

[1 1 1 0 1 0 0 0 1 1 0 0 1 1 1 1 0 1 0 1]


Generate matrix of 20 set of 5 binary number (20 x 5 shape matrix)

In [81]:
x =  np.random.randint(0,2,size=(20,5))
print(x)

[[0 1 0 0 0]
 [1 1 0 1 1]
 [1 1 0 0 0]
 [0 1 1 0 0]
 [1 0 1 0 0]
 [0 0 0 0 0]
 [1 0 1 1 0]
 [0 0 0 1 0]
 [0 1 0 1 1]
 [1 1 0 0 1]
 [0 0 1 0 1]
 [0 1 0 1 1]
 [0 1 0 0 1]
 [0 0 0 1 0]
 [1 1 1 1 1]
 [1 1 1 1 0]
 [0 1 0 0 1]
 [0 0 0 0 0]
 [1 0 0 0 1]
 [1 0 0 1 1]]


Generate two array with 50 random real number

In [ ]:
x = 
y =

## Convert Numpy to Tensor

## Generate Tensors

Generate Sparse tensor

Convert the sparse tensor to dense tensor

## Tensor operation

Find the squared difference between two vector, and sum across elements

# Custom Loss Function

## Binary Cross Entropy Loss

Initialize value

In [70]:
y_true=np.random.randint(0,2,20)
y_pred = np.random.uniform(size=20)

In [71]:
y_pred


array([0.91277071, 0.44755953, 0.58434839, 0.19997227, 0.45341156,
       0.18877299, 0.8755235 , 0.12836663, 0.56007073, 0.51463841,
       0.42928818, 0.88401672, 0.10511991, 0.06423587, 0.23464224,
       0.97227633, 0.76515601, 0.26912828, 0.68013925, 0.66973501])

Keras Function

In [75]:
bce = keras.losses.BinaryCrossentropy(from_logits=False)
bce(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=0.8920551538467407>

Binary Cross Entropy loss is defined by
\begin{equation}
L=-(y.log(\hat{y})+(1-y).log(1-\hat{y}))
\end{equation}

In [77]:
def bce_fn(y_true, y_pred):
  epsilon = 1e-07
  error = y_true*math_ops.log(y_pred)
  error += (1-y_true+epsilon)*math_ops.log(1-y_pred+epsilon)
  error = -1*tf.math.reduce_mean(error)
  return error

In [78]:
bce_fn(y_true,y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=0.8920553523918808>

## KL-Divergence

## MSE Loss

## MAPE Loss

# Custom Metrics

## F1-Score