# Week 1: Day 3 PM // Numpy

# Numpy Introduction

NumPy (**Num**erical **Py**thon) is an open-source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. 

The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

**Installing NumPy**

If you already have Python, you can install NumPy with:

`conda install numpy`

or

`pip install numpy`

**How to import NumPy**

Any time you want to use a package or library in your code, you first need to make it accessible.

In order to start using NumPy and all of the functions available in NumPy, you’ll need to import it. This can be easily done with this import statement:

> **`import numpy as np`**

(We shorten “numpy” to “np” in order to save time and also to keep code standardized so that anyone working with your code can easily understand and run it.)

**Why use NumPy?**

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is far more convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types, which allows the code to be optimized even further.

## Terminology

**What is an array?**

An array is a central data structure of the NumPy library. It’s a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype (data type).

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

One way we can initialize NumPy arrays is from nested Python lists.

`a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])`

We can access the elements in the array using square brackets. When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.

`print(a[0])`

Output:

`[1 2 3 4]`

More information about arrays

> 1D array, 2D array, ndarray, vector, matrix

You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single column, while a matrix refers to an array with multiple columns.

**What are the attributes of an array?**

An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

```py
[[0., 0., 0.],
 [1., 1., 1.]]
```

Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3.

Just like in other Python container objects, the contents of an array can be accessed and modified by indexing or slicing the array. Different arrays can share the same data, so changes made on one array might be visible in another.

Array attributes reflect information intrinsic to the array itself. If you need to get, or even set, properties of an array without creating a new array, you can often access an array through its attributes.

**What’s the difference between a Python list and a NumPy array?**

NumPy gives you an enormous range of fast and efficient numerically-related options. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogenous. The mathematical operations that are meant to be performed on arrays wouldn’t be possible if the arrays weren’t homogenous.

## Array

### Creating Array

```py
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()
```

To create a NumPy array, you can use the function `np.array()`.

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.


In [ ]:
import numpy as np

a = np.array([1, 2, 3])

In [ ]:
a

array([1, 2, 3])

There are often cases when we want NumPy to initialize the values of the array for us. NumPy provides methods like ones(), zeros(), and etc for these cases. We just pass them the number of elements we want it to generate:

In [ ]:
# you can easily create an array filled with 0s:

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
# Or an array filled with 1s:

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
# Or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of the memory.

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
# You can create an array with a range of elements

print(np.arange(4))
print(np.arange(0,10,2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


What `arange([start],stop,[step])` does is that it arranges numbers from starting to stop, in steps of step. Here is what it means for `np.arange(0,10,2)`:

return an np list starting from 0 all the way upto 10 but don’t include 10 and increment numbers by 2 each time.

important thing remember here is that the stopping number is not going to be included in the list.
another example:

```py
np.arange(2,29,5)

>>> array([ 2,  7, 12, 17, 22, 27])
```

### List Vs Numpy

In [ ]:
height= [1.73, 1.68, 1.71, 1.86, 1.87]
weight= [65.4, 59.2, 63.2, 88.4, 68.7]

#Body Mass Index (BMI)
weight/height **2   # error

TypeError: ignored

In [ ]:
import numpy as np
height= [1.73, 1.68, 1.71, 1.86, 1.87]
weight= [65.4, 59.2, 63.2, 88.4, 68.7]
np_height= np.array(height)
np_weight= np.array(weight)

np_weight/np_height **2  

array([21.85171573, 20.97505669, 21.61348791, 25.55208695, 19.64597215])

### Add, Remove, and Sort

```py
np.append()
np.delete()
np.sort()
```

If you start with this array:

`arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])`

You can add elements to your array any time with `np.append()`. Make sure to specify the array and the elements you want to include.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

You can delete an element with `np.delete()`. If you want to delete the element in position 1 of your array, you can run:

In [ ]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

Sorting an element is simple with `np.sort()`. You can specify the axis, kind, and order when you call the function.

If you start with this array:

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

You can quickly sort the numbers in ascending order with:

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and Size

```py
ndarray.ndim()
ndarray.size()
ndarray.shape()
```

`ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

`ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

`ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2D array with 2 rows and 3 columns, the shape of your array is (2,3).

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [ ]:
arr_one.ndim

2

In [ ]:
arr_one.size

5

In [ ]:
arr_one.shape

(1, 5)

### Reshape

```py
np.reshape()
```

Using `np.reshape()` will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

If you start with this array:

In [ ]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


You can use reshape() to reshape your array. For example, you can reshape this array to an array with three rows and two columns:

In [ ]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

With np.reshape, you can specify a few optional parameters:

`numpy.reshape(a, newshape, order)`

- **a** is the array to be reshaped.
- **newshape** is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.
- **order**: ‘C’ means to read/write the elements using C-like index order, ‘F’ means to read/write the elements using Fortran-like index order, ‘A’ means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

### Convert 1D to 2D

```py
np.newaxis
np.expand_dims
```

You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

Using `np.newaxis` will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

For example, if you start with this array:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [ ]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [ ]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

For example, if you start with this array:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

### Indexing and Slicing

You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [ ]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

For example, if you start with this array:

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [ ]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [ ]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

```py
slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()
```

You can easily use create a new array from a section of an existing array. Let’s say you have this array:

`array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])`

You can create a new array from a section of your array any time by specifying where you want to slice your array.


In [ ]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays:

a_1:

```py
array([[1, 1],
     [2, 2]])
```
and a_2:

```py
array([[3, 3],
     [4, 4]])
```

You can stack them vertically with `vstack`

In [ ]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [ ]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [ ]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using hsplit. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

Let’s say you have this array:

```py
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
```

In [ ]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [ ]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

You can use the view method to create a new array object that looks at the same data as the original array (a shallow copy)

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations

`Addition, subtraction, multiplication, division, and more`

Once you’ve created your arrays, you can start to work with them. Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”.

You can add the arrays together with the plus sign.

`data + ones`

You can, of course, do more than just addition.

```py
data - ones
data * data
data / data
```

Basic operations are simple with NumPy. If you want to find the sum of the elements in an array, you’d use sum(). This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [ ]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

To add the rows or the columns in a 2D array, you would specify the axis.

If you start with this array:

In [ ]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [ ]:
# You can sum the rows

b.sum(axis=0)

array([3, 3])

In [ ]:
# You can sum the columns

b.sum(axis=1)

array([2, 4])

In [ ]:
data = np.array([1, 2])
data

array([1, 2])

In [ ]:
ones = np.ones(2)
ones

array([1., 1.])

In [ ]:
data + ones

array([2., 3.])

In [ ]:
data * data

array([1, 4])

In [ ]:
data / data

array([1., 1.])

### More Array Operations

`Maximum, minimum, sum, mean, product, standard deviation, and more`

NumPy also performs aggregation functions. In addition to `min`, `max`, and `sum`, you can easily run `mean` to get the average, `prod` to get the result of multiplying the elements together, `std` to get the standard deviation, and more.

```py
data.max()
data.min()
data.sum()
```


In [ ]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


It’s very common to want to aggregate along a row or column. By default, every NumPy aggregation function will return the aggregate of the entire array.

In [ ]:
A.sum()

4.8595784

In [ ]:
A.min()

0.05093587

In [ ]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [ ]:
A.max()

0.82485143

In [ ]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [ ]:
A.std()

0.21392120766089617

The four values listed above correspond to the number of columns in your array. With a four-column array, you will get four values as your result.